### PR TITLE
add resources

### PR DESCRIPTION
**Pull request by xjtustt**

### CODE REVIEW

**Comment by rcsherro** [comment]
here are my comments and suggestions.

**metering_controller.go**
- line 545 - remove this line since it is not used: "log.WithValues..."
- line 549 - make "v1.metering.ibm.com" a constant so it will easier to change in the future
- line 550 - add "Namespace: instance.Namespace" (see serviceForDataMgr for an example)
- line 560 - change 'Namespace: "ibm-common-services"' to 'Namespace: instance.Namespace' 
- line 567 - change "deploymentForDataMgr returns..." to "deploymentForReport returns..."
- line 573 - add some code to set the image for the container. The image registry can be specified in the CR. (see deploymentForDataMgr for an example)
- line 593 - change 'ServiceAccountName: "ibm-metering-operator"' to 'ServiceAccountName: res.GetServiceAccountName()' (see deploymentForDataMgr for an example)
- line 608 - change "... for DM Deployment" to "... for Report Deployment"

**reconcile.go**

- line 86 - why is Namespace set to ""?
- line 86 - make "v1.metering.ibm.com" a constant so it will easier to change in the future
- line 88 - change "Create a new deployment" to "Create a new APIService"
- line 108 - add some code to determine if the resource has changed

**Comment by morvencao** [comment]
ok-to-test

**Pull request merged**
